Add Environment variables page
ditkrg/dit-digital-service-manual pull request #37
Opened 2023-03-27 13:44 UTC by 5h4k4r

Resolves #36

2023-03-27 21:01 UTC, MohamadTahir commented on kubernetes/fleet.yaml
I believe this file should be in the root dir.

2023-04-04 13:49 UTC, MohamadTahir commented on docs/Software Development/06-Environment Variables.md
> +| DATABASE\_\_URL            | The URI format for the connection string of database server               |
add DATABASE__CONNECTION_STRING

2023-04-04 13:50 UTC, MohamadTahir commented on docs/Software Development/06-Environment Variables.md
> +| CAS\_\_URL                 | The URI format for the connection string of database server               |
Fix the description of these environment variables

2023-04-04 13:53 UTC, MohamadTahir commented on docs/Software Development/06-Environment Variables.md
> +In addition to these common environment variables, some applications may have specific environment variables that are related to their functionality or dependencies. These variables are prefixed with
no need for this section.

2023-04-04 14:07 UTC, MohamadTahir commented on docs/Software Development/06-Environment Variables.md
> +| S3\_\_REGION                 | The AWS region of the S3 bucket                                           |
S3__REGION is not needed.

2023-04-04 14:34 UTC, broosk1993 requested changes

2023-04-04 14:34 UTC, broosk1993 commented on docs/Software Development/06-Environment Variables.md
> +| DATABASE\_\_CONNECTIONSTRING | The connection string of database server                                  |
Should be DATABASE__CONNECTION_STRING

2023-04-04 14:34 UTC, broosk1993 commented on docs/Software Development/06-Environment Variables.md
> +| DATABASE\_\_CONNECTIONSTRING | The connection string of database server                                  |
Adds also REDIS__CONNECTION_STRING

2023-04-27 14:52 UTC, MohamadTahir approved these changes

2023-05-03 10:46 UTC, broosk1993 approved these changes

2023-05-03 10:46 UTC, merged